/**
 * Every piece of interface text shown to the student. The study material is in Portuguese,
 * so all Portuguese wording lives under src/content and the application code stays in English.
 */
export const T = {
  common: {
    close: 'Fechar',
    menu: '← Menu',
    campus: 'Campus Guarapuava',
    university: 'Universidade Tecnológica Federal do Paraná - UTFPR',
    course: 'Campus Guarapuava · TSI (Sistemas para Internet)',
    difficulty: { easy: '🟢 Fácil', medium: '🟡 Média', hard: '🔴 Difícil' },
    step: { previous: 'Passo anterior', play: 'Reproduzir', pause: 'Pausar', next: 'Próximo passo', restart: 'Recomeçar' },
  },
  menu: {
    seal: 'Exame de suficiência · SI104C · 70 horas',
    titleStart: 'Engenharia de',
    titleHighlight: 'Software',
    lead:
      'Toda a ementa da disciplina em <b>8 tópicos</b>, na ordem do plano de ensino da UTFPR. ' +
      'De um lado, o conceito explicado com o que <b>cai na prova</b>; do outro, um <b>laboratório animado</b> ' +
      'para ver o processo acontecendo. Depois, questões comentadas, dissertativas com resposta-modelo e simulado cronometrado.',
    examButton: '📝 Fazer o simulado',
    flashcardsButton: '🃏 Flashcards',
    cheatButton: '📋 Cola da matéria',
    overall: (done: number, total: number): string => done + ' de ' + total + ' itens dominados',
    overallLabel: 'Seu progresso na ementa',
    unit: (unit: number): string => 'Unidade ' + unit,
    study: 'Estudar →',
    cardCounts: (lessons: number, questions: number): string => lessons + ' conceitos · ' + questions + ' questões',
    examCardTitle: 'Simulado cronometrado',
    examCardText:
      'Questões sorteadas de todos os tópicos, relógio correndo e correção comentada no final, com nota de 0 a 10 e o mapa dos seus pontos fracos.',
    examCardAction: 'Abrir o simulado →',
    examBest: (grade: string): string => 'Melhor nota: ' + grade,
    examNone: 'Nenhum simulado feito ainda',
    how: [
      '<b>Leia</b> o card do conceito: definição, o que cai na prova e o macete para lembrar.',
      '<b>Clique ▶</b> para ver o conceito em movimento no laboratório ao lado e brinque com ele.',
      '<b>Responda</b> as questões e as dissertativas; no fim, faça o simulado cronometrado.',
    ],
    authorCaption: 'Apresentado por',
    authorPhotoAlt: 'Foto de Ricardo Martins de Oliveira',
    professorCaption: 'Docente avaliadora',
    referencesTitle: '📚 Referências: livros e vídeos',
    referencesLead: 'Os livros do plano de ensino, edições atuais, leituras gratuitas e videoaulas para cada tópico. Use para tirar dúvidas e para conferir o conteúdo na fonte.',
    booksTitle: '📖 Livros e leituras',
    videosTitle: '🎬 Videoaulas',
    readOnline: 'ler on-line ↗',
    videoCount: (count: number): string => count + (count === 1 ? ' vídeo' : ' vídeos'),
    bookCount: (count: number): string => count + (count === 1 ? ' item' : ' itens'),
    referencesButton: '📚 Referências',
    reset: 'Zerar meu progresso',
    resetConfirm: 'Apagar todo o progresso salvo neste navegador (conceitos, questões, flashcards e simulados)?',
    resetDone: 'Progresso zerado',
    cheatTitle: '📋 Cola da matéria',
  },
  topic: {
    tabLessons: '📘 Conceitos',
    tabQuestions: '🎯 Questões',
    tabOpen: '✍️ Dissertativas',
    tabFlashcards: '🃏 Flashcards',
    examTip: '🎯 Cai na prova',
    mnemonic: '🧠 Macete',
    funFact: '🤓 Você sabia?',
    understood: 'Entendi',
    lessonOf: (index: number, total: number): string => index + '/' + total,
    progress: (percent: number): string => percent + '% dominado',
    previous: '← Anterior',
    next: 'Próximo →',
    questionsIntro: (right: number, total: number): string => right + ' de ' + total + ' acertadas',
    questionsHint: 'As alternativas mudam de ordem a cada tentativa: decore o conceito, não a letra.',
    right: 'Correto!',
    wrong: 'Não é essa.',
    rightAnswerWas: 'Resposta certa:',
    retry: 'Tentar de novo',
    openIntro:
      'Prova de suficiência costuma ter questão discursiva. Escreva a sua resposta <b>antes</b> de abrir a resposta-modelo e confira os pontos que não podem faltar.',
    openPlaceholder: 'Escreva aqui a sua resposta, como se fosse na prova...',
    openReveal: 'Ver resposta-modelo',
    openModel: 'Resposta-modelo',
    openKeyPoints: 'Não pode faltar na resposta',
    openOk: '✓ Eu acertaria',
    openReview: '↺ Preciso revisar',
    openStatusOk: 'Dominada',
    openStatusReview: 'Revisar',
    flashHint: 'Clique no card para virar.',
    flashTrain: 'Treinar este tópico no modo flashcards →',
    labHint: 'Laboratório',
    videosTitle: '🎬 Para ver em vídeo',
    videosLead: 'Videoaulas sobre este tópico. A lista completa de livros e vídeos está em Referências, na tela inicial.',
  },
  exam: {
    title: 'Simulado',
    subtitle: 'Engenharia de Software · SI104C',
    hubLead:
      'Escolha o tamanho da prova e os tópicos. As questões e a ordem das alternativas são sorteadas a cada tentativa. ' +
      'Não há correção durante a prova: o gabarito comentado aparece no final.',
    modes: [
      { id: 'quick', icon: '⚡', title: 'Rápido', questions: 10, minutes: 12, description: 'Aquecimento para testar um ou dois tópicos.' },
      { id: 'standard', icon: '📝', title: 'Padrão', questions: 20, minutes: 25, description: 'Formato equilibrado, bom para o dia a dia de estudo.' },
      { id: 'full', icon: '🏆', title: 'Completo', questions: 40, minutes: 50, description: 'Cobre a ementa inteira. Faça na véspera da prova.' },
    ],
    modeInfo: (questions: number, minutes: number): string => questions + ' questões · ' + minutes + ' min',
    topicsTitle: 'Tópicos que entram na prova',
    selectAll: 'Marcar todos',
    start: '▶ Começar a prova',
    needTopic: 'Marque pelo menos um tópico',
    historyTitle: 'Últimas tentativas',
    historyEmpty: 'Suas tentativas aparecem aqui.',
    historyRow: (correct: number, total: number, clock: string): string => correct + '/' + total + ' certas em ' + clock,
    quit: '← Abandonar',
    quitConfirm: 'Sair agora descarta esta tentativa. Quer mesmo abandonar a prova?',
    answered: (done: number, total: number): string => done + '/' + total + ' respondidas',
    finish: '🏁 Finalizar prova',
    finishConfirm: (missing: number): string =>
      missing === 0 ? 'Finalizar a prova e ver o resultado?' : 'Ainda há ' + missing + ' questão(ões) em branco. Finalizar mesmo assim?',
    questionOf: (index: number, total: number): string => 'Questão ' + index + ' de ' + total,
    flag: '🚩 Marcar para revisar',
    unflag: '🚩 Marcada',
    previous: '← Anterior',
    next: 'Próxima →',
    keys: 'Teclas: <kbd>1</kbd>–<kbd>4</kbd> escolhem a alternativa · <kbd>←</kbd> <kbd>→</kbd> navegam',
    timeUp: 'Tempo esgotado! Prova finalizada.',
    passed: 'Aprovado no simulado',
    failed: 'Ainda não: abaixo de 6,0',
    grade: 'Nota',
    resultLine: (correct: number, total: number, clock: string): string => correct + ' de ' + total + ' questões certas · tempo usado ' + clock,
    passNote: 'A UTFPR aprova com nota a partir de 6,0. Mire em 8,0 no simulado para ir à prova com folga.',
    byTopic: 'Desempenho por tópico',
    studyTopic: 'Revisar →',
    review: 'Gabarito comentado',
    reviewOnlyWrong: 'Mostrar só as que errei',
    yourAnswer: 'Sua resposta:',
    blank: 'em branco',
    correctAnswer: 'Resposta certa:',
    again: '↺ Nova tentativa',
    backToMenu: 'Voltar ao menu',
  },
  flash: {
    title: 'Flashcards',
    subtitle: 'Revisão relâmpago por repetição',
    all: 'Todos os tópicos',
    onlyUnknown: 'Só os que ainda não sei',
    counter: (index: number, total: number): string => 'Card ' + index + ' de ' + total,
    known: (known: number, total: number): string => known + ' de ' + total + ' já dominados',
    front: 'Pergunta',
    back: 'Resposta',
    flip: 'Virar',
    dontKnow: 'Ainda não sei',
    know: 'Já sei',
    keys: '<kbd>espaço</kbd> vira · <kbd>←</kbd> ainda não sei · <kbd>→</kbd> já sei',
    doneTitle: 'Baralho concluído!',
    doneText: (known: number, total: number): string => 'Você marcou ' + known + ' de ' + total + ' cards como dominados nesta rodada.',
    restart: '↺ Embaralhar e repetir',
    emptyTitle: 'Nada para revisar aqui',
    emptyText: 'Você já marcou todos os cards deste filtro como dominados. Desmarque o filtro para rever tudo.',
  },
  lab: {
    tour: '▶ Percorrer de baixo para cima',
    stackHint: 'Clique em uma camada para ver o que ela significa.',
    classifier: {
      round: (current: number, total: number): string => 'Card ' + current + ' de ' + total,
      streak: (count: number): string => '🔥 ' + count + ' seguidas',
      correct: 'Isso!',
      wrong: (rightLabel: string): string => 'Era "' + rightLabel + '".',
      next: 'Próximo',
      finishedTitle: (hits: number, total: number): string => 'Você acertou ' + hits + ' de ' + total,
      finishedPerfect: 'Gabaritou! Esse conceito está dominado.',
      finishedReview: 'Releia os que escaparam e jogue de novo: os cards são embaralhados a cada rodada.',
      playAgain: '↺ Jogar de novo',
      keyboardHint: 'Dica: as teclas numéricas escolhem a categoria e <kbd>Enter</kbd> avança.',
    },
  },
};
