import type { ClassifierConfig } from '../../components/ClassifierGame';
import type { SprintConfig } from '../../labs/SprintPanel';

export const agileLabTitle: string = 'Laboratório · Time ágil';

export const sprintSimulation: SprintConfig = {
  id: 'sprint',
  label: '🏃 Sprint',
  title: 'Uma Sprint do começo ao fim',
  intro: 'Acompanhe os cartões andando no quadro, <b>quem age</b> em cada momento e o <b>burndown</b> descendo. Use ⏮ ▶ ⏭ para ir no seu ritmo.',
  days: 5,
  columns: { backlog: 'Product Backlog', todo: 'A fazer', doing: 'Em andamento', done: 'Concluído' },
  roles: {
    po: { name: 'Product Owner', duty: 'valor e prioridade' },
    sm: { name: 'Scrum Master', duty: 'processo e impedimentos' },
    dev: { name: 'Time de desenvolvimento', duty: 'constrói o incremento' },
  },
  events: [
    { id: 'backlog', name: 'Product Backlog' },
    { id: 'planning', name: 'Sprint Planning' },
    { id: 'daily', name: 'Daily Scrum' },
    { id: 'review', name: 'Sprint Review' },
    { id: 'retrospective', name: 'Retrospective' },
  ],
  stories: [
    { id: 's1', title: 'Login com e-mail e senha', points: 3 },
    { id: 's2', title: 'Catálogo de produtos', points: 5 },
    { id: 's3', title: 'Carrinho de compras', points: 5 },
    { id: 's4', title: 'Pagamento por Pix', points: 8 },
    { id: 's5', title: 'Avaliação de produtos', points: 3 },
    { id: 's6', title: 'Lista de desejos', points: 2 },
    { id: 's7', title: 'Login com conta Google', points: 3, appearsAt: 7 },
  ],
  steps: [
    {
      event: 'backlog',
      day: null,
      actors: ['po'],
      caption: '<b>Product Backlog.</b> O <b>Product Owner</b> mantém a lista <b>ordenada</b> por valor de negócio: o que está no topo é o mais importante e o mais detalhado. Os números são <b>story points</b>, estimados pelo time.',
    },
    {
      event: 'planning',
      day: 0,
      actors: ['po', 'sm', 'dev'],
      moves: [{ story: 's1', to: 'todo' }, { story: 's2', to: 'todo' }, { story: 's3', to: 'todo' }],
      caption: '<b>Sprint Planning.</b> O PO apresenta os itens do topo; o <b>time decide quanto cabe</b> com base na sua velocidade (13 pontos). Os itens escolhidos e o plano para entregá-los formam o <b>Sprint Backlog</b>, guiados pela <b>meta da Sprint</b>.',
    },
    {
      event: 'daily',
      day: 1,
      actors: ['dev'],
      moves: [{ story: 's1', to: 'doing' }, { story: 's2', to: 'doing' }],
      caption: '<b>Daily Scrum · dia 1.</b> Em 15 minutos, o time sincroniza o trabalho: o que fiz, o que vou fazer, há impedimentos? O próprio time <b>puxa</b> as tarefas, ninguém as distribui.',
    },
    {
      event: 'daily',
      day: 2,
      actors: ['dev'],
      moves: [{ story: 's1', to: 'done' }, { story: 's3', to: 'doing' }],
      caption: '<b>Dia 2.</b> O login atende à <b>Definição de Pronto</b> e vai para "Concluído". O burndown desce 3 pontos.',
    },
    {
      event: 'daily',
      day: 3,
      actors: ['sm', 'dev'],
      blocked: ['s2'],
      caption: '<b>Dia 3 · impedimento.</b> O catálogo depende de um acesso ao banco que não foi liberado. O <b>Scrum Master</b> entra em cena para <b>remover o impedimento</b>. Repare: o burndown fica <b>reto</b>, acima da linha ideal.',
    },
    {
      event: 'daily',
      day: 4,
      actors: ['dev'],
      moves: [{ story: 's2', to: 'done' }],
      caption: '<b>Dia 4.</b> Impedimento removido, catálogo concluído. O time volta a se aproximar da linha ideal.',
    },
    {
      event: 'daily',
      day: 5,
      actors: ['dev'],
      moves: [{ story: 's3', to: 'done' }],
      caption: '<b>Dia 5.</b> Carrinho concluído: o trabalho restante chega a <b>zero</b> e a meta da Sprint foi atingida.',
    },
    {
      event: 'review',
      day: null,
      actors: ['po', 'dev'],
      caption: '<b>Sprint Review.</b> O time demonstra o <b>incremento</b> às partes interessadas. Elas pedem login com conta Google: o feedback vira um <b>novo item no Product Backlog</b>. Aqui se inspeciona o <b>produto</b>.',
    },
    {
      event: 'retrospective',
      day: null,
      actors: ['po', 'sm', 'dev'],
      caption: '<b>Sprint Retrospective.</b> O time Scrum inspeciona o <b>processo</b>: o que funcionou, o que atrapalhou (o acesso ao banco!) e que melhoria será adotada na próxima Sprint.',
    },
    {
      event: 'backlog',
      day: null,
      actors: ['po'],
      caption: '<b>Próxima Sprint.</b> A <b>velocidade</b> medida (13 pontos) alimenta o próximo planejamento, e o PO reordena o backlog com o que aprendeu. O ciclo recomeça.',
    },
  ],
  pointsLabel: 'pts',
  blockedLabel: 'bloqueado',
  burndownTitle: 'Burndown da Sprint',
  idealLabel: 'ideal',
  realLabel: 'real',
  dayLabel: 'dia',
};

export const rolesGame: ClassifierConfig = {
  id: 'roles',
  label: '👥 Quem faz?',
  title: 'Quem é o responsável no Scrum?',
  intro: 'Atribua cada responsabilidade ao papel correto. É a pegadinha mais comum sobre Scrum.',
  rounds: 10,
  categories: [
    { id: 'po', label: 'Product Owner', hint: 'valor e prioridade', color: 'var(--yellow)' },
    { id: 'sm', label: 'Scrum Master', hint: 'processo e impedimentos', color: 'var(--green)' },
    { id: 'dev', label: 'Time de desenvolvimento', hint: 'constrói o incremento', color: 'var(--blue)' },
  ],
  items: [
    { text: 'Ordenar os itens do Product Backlog conforme o valor de negócio.', category: 'po', explanation: 'A ordenação do Product Backlog é responsabilidade exclusiva do Product Owner.' },
    { text: 'Remover os impedimentos que atrapalham o progresso do time.', category: 'sm', explanation: 'Remover impedimentos é serviço do Scrum Master ao time.' },
    { text: 'Estimar o esforço dos itens do backlog.', category: 'dev', explanation: 'Quem faz o trabalho é quem estima: o time de desenvolvimento.' },
    { text: 'Decidir como transformar os itens selecionados em um incremento "pronto".', category: 'dev', explanation: 'O time é auto-organizável: ninguém de fora diz como fazer o trabalho.' },
    { text: 'Garantir que o Scrum seja compreendido e aplicado por todos.', category: 'sm', explanation: 'O Scrum Master é o guardião do framework.' },
    { text: 'Representar os interesses dos clientes e das partes interessadas perante o time.', category: 'po', explanation: 'O PO é a voz do negócio dentro do time Scrum.' },
    { text: 'Decidir quantos itens cabem na Sprint.', category: 'dev', explanation: 'A quantidade de trabalho selecionada para a Sprint é decisão do time de desenvolvimento.' },
    { text: 'Facilitar os eventos do Scrum quando solicitado ou necessário.', category: 'sm', explanation: 'O Scrum Master facilita os eventos e ensina o time a mantê-los dentro do time-box.' },
    { text: 'Aceitar ou rejeitar o trabalho entregue ao fim da Sprint.', category: 'po', explanation: 'O PO verifica se o incremento atende aos critérios de aceitação.' },
    { text: 'Proteger o time de interferências externas durante a Sprint.', category: 'sm', explanation: 'O Scrum Master ajuda quem está de fora a entender quais interações com o time são úteis.' },
    { text: 'Cancelar uma Sprint cuja meta se tornou obsoleta.', category: 'po', explanation: 'Somente o Product Owner tem autoridade para cancelar a Sprint.' },
    { text: 'Atualizar o Sprint Backlog e o quadro de tarefas durante a Sprint.', category: 'dev', explanation: 'O Sprint Backlog pertence ao time de desenvolvimento.' },
    { text: 'Escrever e esclarecer os itens do Product Backlog para que o time os compreenda.', category: 'po', explanation: 'O PO garante que o backlog seja visível, transparente e claro.' },
  ],
};

export const elementsGame: ClassifierConfig = {
  id: 'elements',
  label: '📦 Elementos',
  title: 'Papel, evento ou artefato?',
  intro: 'O Scrum tem 3 papéis, 5 eventos e 3 artefatos. Classifique cada elemento.',
  categories: [
    { id: 'role', label: 'Papel', hint: 'quem', color: 'var(--yellow)' },
    { id: 'event', label: 'Evento', hint: 'quando', color: 'var(--blue)' },
    { id: 'artifact', label: 'Artefato', hint: 'o quê', color: 'var(--green)' },
  ],
  items: [
    { text: 'Product Backlog', category: 'artifact', explanation: 'Lista ordenada de tudo o que pode ser necessário no produto.' },
    { text: 'Daily Scrum', category: 'event', explanation: 'Reunião diária de 15 minutos do time de desenvolvimento.' },
    { text: 'Scrum Master', category: 'role', explanation: 'Líder servidor do time Scrum.' },
    { text: 'Incremento', category: 'artifact', explanation: 'Soma dos itens concluídos, em estado utilizável.' },
    { text: 'Sprint Review', category: 'event', explanation: 'Inspeção do incremento com as partes interessadas.' },
    { text: 'Product Owner', category: 'role', explanation: 'Responsável por maximizar o valor do produto.' },
    { text: 'Sprint Backlog', category: 'artifact', explanation: 'Itens selecionados para a Sprint mais o plano para entregá-los.' },
    { text: 'Sprint Retrospective', category: 'event', explanation: 'Inspeção do processo de trabalho do time.' },
    { text: 'Time de desenvolvimento', category: 'role', explanation: 'Profissionais que constroem o incremento.' },
    { text: 'Sprint Planning', category: 'event', explanation: 'Planejamento do que será entregue e de como o trabalho será feito.' },
    { text: 'Sprint', category: 'event', explanation: 'A Sprint é o evento que contém todos os outros, com time-box de até um mês.' },
  ],
};

export const methodsGame: ClassifierConfig = {
  id: 'methods',
  label: '🧗 Scrum, XP ou Kanban?',
  title: 'De qual método é essa prática?',
  intro: 'Cada método ágil tem a sua marca registrada. Identifique a origem de cada elemento.',
  rounds: 12,
  categories: [
    { id: 'scrum', label: 'Scrum', hint: 'gestão em Sprints', color: 'var(--green)' },
    { id: 'xp', label: 'XP', hint: 'excelência técnica', color: 'var(--purple)' },
    { id: 'kanban', label: 'Kanban', hint: 'fluxo contínuo', color: 'var(--yellow)' },
  ],
  items: [
    { text: 'Programação em pares', category: 'xp', explanation: 'Dois programadores em uma máquina: prática clássica do XP.' },
    { text: 'Limitar o trabalho em andamento (WIP)', category: 'kanban', explanation: 'A prática central do Kanban.' },
    { text: 'Sprint Retrospective', category: 'scrum', explanation: 'Um dos cinco eventos do Scrum.' },
    { text: 'Desenvolvimento orientado a testes (TDD)', category: 'xp', explanation: 'Escrever o teste antes do código é prática do XP.' },
    { text: 'Product Owner', category: 'scrum', explanation: 'Um dos três papéis do Scrum.' },
    { text: 'Sistema puxado, sem iterações com tempo fixo', category: 'kanban', explanation: 'No Kanban, o trabalho flui continuamente e é puxado conforme a capacidade.' },
    { text: 'Refatoração contínua', category: 'xp', explanation: 'Melhorar a estrutura do código sem mudar o comportamento.' },
    { text: 'Metáfora do sistema', category: 'xp', explanation: 'Uma história compartilhada que descreve como o sistema funciona.' },
    { text: 'Daily de 15 minutos', category: 'scrum', explanation: 'A Daily Scrum tem time-box de 15 minutos.' },
    { text: 'Medir lead time e cycle time do fluxo', category: 'kanban', explanation: 'Métricas de fluxo são a base da melhoria no Kanban.' },
    { text: 'Propriedade coletiva do código', category: 'xp', explanation: 'Qualquer par pode alterar qualquer parte do código.' },
    { text: 'Semana de 40 horas (ritmo sustentável)', category: 'xp', explanation: 'Prática do XP contra horas extras constantes.' },
    { text: 'Incremento potencialmente utilizável ao fim de cada iteração de até um mês', category: 'scrum', explanation: 'É o resultado de toda Sprint.' },
    { text: 'Origem no Sistema Toyota de Produção, com cartões de sinalização', category: 'kanban', explanation: 'Kanban significa "cartão" e nasceu na manufatura enxuta.' },
    { text: 'Jogo do planejamento', category: 'xp', explanation: 'Cliente prioriza as histórias e desenvolvedores estimam.' },
    { text: 'Sprint Backlog', category: 'scrum', explanation: 'Um dos três artefatos do Scrum.' },
  ],
};
