import type { ClassifierConfig } from '../../components/ClassifierGame';
import type { DiagramConfig } from '../../components/DiagramPlayer';

export const lifecyclesLabTitle: string = 'Laboratório · Simulador de modelos de processo';

const WHEN: string = 'Quando usar';
const STRENGTH: string = 'Ponto forte';
const RISK: string = 'Ponto fraco';

export const modelsDiagram: DiagramConfig = {
  id: 'models',
  label: '🔄 Simulador',
  title: 'Modelos de ciclo de vida em movimento',
  models: [
    {
      id: 'waterfall',
      name: 'Cascata',
      summary: 'Fases em sequência: a saída aprovada de uma é a entrada da próxima. As setas tracejadas são as <b>voltas</b>, que o modelo admite, mas que custam caro.',
      width: 640,
      height: 330,
      nodes: [
        { id: 'req', label: 'Definição de\nrequisitos', x: 95, y: 40, width: 150, color: 'var(--blue)' },
        { id: 'design', label: 'Projeto de sistema\ne de software', x: 205, y: 102, width: 150, color: 'var(--teal)' },
        { id: 'impl', label: 'Implementação e\nteste de unidade', x: 315, y: 164, width: 150, color: 'var(--green)' },
        { id: 'integ', label: 'Integração e\nteste de sistema', x: 425, y: 226, width: 150, color: 'var(--purple)' },
        { id: 'maint', label: 'Operação e\nmanutenção', x: 535, y: 288, width: 150, color: 'var(--yellow)' },
      ],
      edges: [
        { from: 'req', to: 'design' },
        { from: 'design', to: 'impl' },
        { from: 'impl', to: 'integ' },
        { from: 'integ', to: 'maint' },
        { from: 'maint', to: 'req', dashed: true, bend: -250, label: 'erro de requisito descoberto tarde' },
      ],
      steps: [
        { nodes: ['req'], caption: '<b>Definição de requisitos.</b> Serviços, restrições e metas são levantados com os usuários e viram a <b>especificação</b> do sistema. No cascata, tudo isso precisa estar fechado <b>antes</b> de seguir.' },
        { nodes: ['design'], edges: [0], caption: '<b>Projeto de sistema e de software.</b> Os requisitos são divididos entre hardware e software e define-se a <b>arquitetura</b> geral.' },
        { nodes: ['impl'], edges: [1], caption: '<b>Implementação e teste de unidade.</b> O projeto vira um conjunto de programas; cada unidade é testada isoladamente contra a sua especificação.' },
        { nodes: ['integ'], edges: [2], caption: '<b>Integração e teste de sistema.</b> As unidades são integradas e testadas como um sistema completo. Só aqui o cliente vê o software funcionando.' },
        { nodes: ['maint'], edges: [3], caption: '<b>Operação e manutenção.</b> Normalmente a fase <b>mais longa</b>: corrigir erros, adaptar o sistema e ampliar os serviços.' },
        { nodes: ['maint', 'req'], edges: [4], caption: '<b>O ponto fraco.</b> Um requisito mal entendido só aparece no fim, e voltar ao começo significa refazer projeto, código e testes. Por isso o cascata só funciona bem com <b>requisitos estáveis</b>.' },
      ],
      facts: [
        { label: WHEN, text: 'Requisitos bem compreendidos e estáveis; contratos que exigem documento por fase.' },
        { label: STRENGTH, text: 'Simples, visível e fácil de gerenciar.' },
        { label: RISK, text: 'Inflexível: mudança tardia é muito cara e o cliente só vê o produto no fim.' },
      ],
    },
    {
      id: 'prototyping',
      name: 'Prototipação',
      summary: 'Um ciclo rápido que se repete até cliente e equipe <b>concordarem sobre os requisitos</b>.',
      width: 640,
      height: 320,
      nodes: [
        { id: 'talk', label: 'Comunicação', x: 320, y: 40, color: 'var(--blue)' },
        { id: 'plan', label: 'Plano rápido', x: 530, y: 125, color: 'var(--teal)' },
        { id: 'model', label: 'Projeto rápido', x: 450, y: 270, color: 'var(--green)' },
        { id: 'build', label: 'Construção\ndo protótipo', x: 190, y: 270, color: 'var(--purple)' },
        { id: 'feedback', label: 'Entrega e\nfeedback', x: 110, y: 125, color: 'var(--yellow)' },
        { id: 'proto', label: 'Protótipo', x: 320, y: 160, width: 120, height: 54, shape: 'ellipse', color: 'var(--pink)' },
      ],
      edges: [
        { from: 'talk', to: 'plan', bend: -18 },
        { from: 'plan', to: 'model', bend: -18 },
        { from: 'model', to: 'build', bend: -18 },
        { from: 'build', to: 'feedback', bend: -18 },
        { from: 'feedback', to: 'talk', bend: -18 },
      ],
      steps: [
        { nodes: ['talk'], caption: '<b>Comunicação.</b> Cliente e equipe definem os objetivos gerais e identificam os requisitos que <b>já</b> são conhecidos e os pontos que precisam ser esclarecidos.' },
        { nodes: ['plan'], edges: [0], caption: '<b>Plano rápido.</b> Planeja-se uma iteração curta de prototipação.' },
        { nodes: ['model'], edges: [1], caption: '<b>Projeto rápido.</b> Foca apenas no que será <b>visível</b> para o usuário: telas, entradas e formatos de saída.' },
        { nodes: ['build', 'proto'], edges: [2], caption: '<b>Construção do protótipo.</b> Uma versão simplificada, feita rápido, sem preocupação com desempenho ou qualidade interna.' },
        { nodes: ['feedback', 'proto'], edges: [3], caption: '<b>Entrega e feedback.</b> O cliente experimenta o protótipo e diz o que serve, o que falta e o que entendeu errado.' },
        { nodes: ['talk'], edges: [4], caption: '<b>Nova volta.</b> O feedback <b>refina os requisitos</b>, e o ciclo se repete quantas vezes forem necessárias.' },
        { nodes: ['proto'], caption: '<b>E depois?</b> Na prototipação <b>descartável</b>, o protótipo é jogado fora e o sistema é construído com qualidade. Na <b>evolucionária</b>, ele é refinado até virar o produto.' },
      ],
      facts: [
        { label: WHEN, text: 'Requisitos vagos; cliente não sabe expressar o que quer; interface incerta.' },
        { label: STRENGTH, text: 'Reduz o risco de construir o sistema errado.' },
        { label: RISK, text: 'Cliente acha que o protótipo é o produto; atalhos viram definitivos.' },
      ],
    },
    {
      id: 'incremental',
      name: 'Incremental',
      summary: 'Cada linha é um <b>mini cascata</b> que termina com uma entrega utilizável. Os incrementos são escalonados no tempo.',
      width: 640,
      height: 290,
      nodes: [
        { id: 'a1', label: 'Análise', x: 55, y: 50, width: 78, height: 36, color: 'var(--blue)' },
        { id: 'p1', label: 'Projeto', x: 145, y: 50, width: 78, height: 36, color: 'var(--blue)' },
        { id: 'c1', label: 'Código', x: 235, y: 50, width: 78, height: 36, color: 'var(--blue)' },
        { id: 't1', label: 'Teste', x: 325, y: 50, width: 78, height: 36, color: 'var(--blue)' },
        { id: 'd1', label: 'Entrega 1\nnúcleo', x: 435, y: 50, width: 104, height: 48, shape: 'ellipse', color: 'var(--blue)' },
        { id: 'a2', label: 'Análise', x: 135, y: 145, width: 78, height: 36, color: 'var(--green)' },
        { id: 'p2', label: 'Projeto', x: 225, y: 145, width: 78, height: 36, color: 'var(--green)' },
        { id: 'c2', label: 'Código', x: 315, y: 145, width: 78, height: 36, color: 'var(--green)' },
        { id: 't2', label: 'Teste', x: 405, y: 145, width: 78, height: 36, color: 'var(--green)' },
        { id: 'd2', label: 'Entrega 2', x: 515, y: 145, width: 104, height: 48, shape: 'ellipse', color: 'var(--green)' },
        { id: 'a3', label: 'Análise', x: 215, y: 240, width: 78, height: 36, color: 'var(--yellow)' },
        { id: 'p3', label: 'Projeto', x: 305, y: 240, width: 78, height: 36, color: 'var(--yellow)' },
        { id: 'c3', label: 'Código', x: 395, y: 240, width: 78, height: 36, color: 'var(--yellow)' },
        { id: 't3', label: 'Teste', x: 485, y: 240, width: 78, height: 36, color: 'var(--yellow)' },
        { id: 'd3', label: 'Entrega 3', x: 585, y: 240, width: 96, height: 48, shape: 'ellipse', color: 'var(--yellow)' },
      ],
      edges: [
        { from: 'a1', to: 'p1' }, { from: 'p1', to: 'c1' }, { from: 'c1', to: 't1' }, { from: 't1', to: 'd1' },
        { from: 'a2', to: 'p2' }, { from: 'p2', to: 'c2' }, { from: 'c2', to: 't2' }, { from: 't2', to: 'd2' },
        { from: 'a3', to: 'p3' }, { from: 'p3', to: 'c3' }, { from: 'c3', to: 't3' }, { from: 't3', to: 'd3' },
        { from: 'd1', to: 'a2', dashed: true, bend: 30 },
        { from: 'd2', to: 'a3', dashed: true, bend: 30 },
      ],
      steps: [
        { nodes: ['a1', 'p1', 'c1', 't1'], edges: [0, 1, 2], caption: '<b>Incremento 1.</b> Os requisitos são <b>priorizados</b>, e o primeiro incremento ataca os mais importantes: o <b>núcleo</b> do produto.' },
        { nodes: ['d1'], edges: [3], caption: '<b>Entrega 1.</b> O cliente já <b>usa</b> uma parte do sistema em produção e começa a obter valor.' },
        { nodes: ['a2', 'p2', 'c2', 't2'], edges: [12, 4, 5, 6], caption: '<b>Incremento 2.</b> A experiência com a primeira entrega serve de <b>protótipo</b> e ajuda a esclarecer os requisitos dos próximos incrementos.' },
        { nodes: ['d2'], edges: [7], caption: '<b>Entrega 2.</b> Nova funcionalidade é <b>integrada</b> ao que já estava em uso.' },
        { nodes: ['a3', 'p3', 'c3', 't3'], edges: [13, 8, 9, 10], caption: '<b>Incremento 3.</b> O processo se repete até o produto estar completo.' },
        { nodes: ['d3', 'd1', 'd2'], edges: [11], caption: '<b>Resultado.</b> O risco de fracasso total é baixo, e os serviços prioritários, entregues primeiro, são os <b>mais testados</b>.' },
      ],
      facts: [
        { label: WHEN, text: 'É preciso entregar valor cedo e os requisitos podem ser priorizados.' },
        { label: STRENGTH, text: 'Feedback real do uso e baixo risco de fracasso total.' },
        { label: RISK, text: 'Difícil mapear requisitos em incrementos de tamanho adequado; a arquitetura pode se degradar.' },
      ],
    },
    {
      id: 'spiral',
      name: 'Espiral',
      summary: 'Cada <b>volta</b> é uma fase do projeto e atravessa os quatro setores. O raio cresce porque o custo acumulado aumenta.',
      width: 640,
      height: 400,
      spiral: { centerX: 320, centerY: 200, startRadius: 16, growth: 44, turns: 3.5 },
      nodes: [
        { id: 'goals', label: '1 · Definir objetivos,\nalternativas e restrições', x: 110, y: 26, shape: 'label', color: 'var(--blue)' },
        { id: 'risks', label: '2 · Avaliar alternativas,\nidentificar e reduzir riscos', x: 530, y: 26, shape: 'label', color: 'var(--red)' },
        { id: 'develop', label: '3 · Desenvolver e validar\no produto deste nível', x: 530, y: 372, shape: 'label', color: 'var(--green)' },
        { id: 'planning', label: '4 · Planejar\na próxima fase', x: 110, y: 372, shape: 'label', color: 'var(--yellow)' },
      ],
      edges: [],
      steps: [
        { nodes: ['goals'], arc: [0, 0.25], caption: '<b>Volta 1 · objetivos.</b> O que se quer alcançar nesta fase? Quais alternativas existem e quais são as restrições?' },
        { nodes: ['risks'], arc: [0.25, 0.5], caption: '<b>Volta 1 · riscos.</b> Cada alternativa é avaliada e os <b>riscos</b> são identificados. Um protótipo ou uma análise reduz a incerteza.' },
        { nodes: ['develop'], arc: [0.5, 0.75], caption: '<b>Volta 1 · desenvolvimento.</b> Produz-se o que esta fase pede: aqui, o <b>conceito de operação</b> e o estudo de viabilidade.' },
        { nodes: ['planning'], arc: [0.75, 1], caption: '<b>Volta 1 · planejamento.</b> O projeto é revisado e decide-se <b>se vale continuar</b>. Se sim, planeja-se a próxima volta.' },
        { nodes: ['goals'], arc: [1, 1.25], caption: '<b>Volta 2 · objetivos.</b> Agora o foco são os <b>requisitos</b> do sistema.' },
        { nodes: ['risks'], arc: [1.25, 1.5], caption: '<b>Volta 2 · riscos.</b> Se o maior risco é a interface, usa-se <b>prototipação</b>. O modelo de desenvolvimento é escolhido <b>conforme o risco</b>.' },
        { nodes: ['develop'], arc: [1.5, 1.75], caption: '<b>Volta 2 · desenvolvimento.</b> Especificação e validação dos requisitos.' },
        { nodes: ['planning'], arc: [1.75, 2], caption: '<b>Volta 2 · planejamento.</b> Plano de desenvolvimento para a volta de projeto.' },
        { nodes: ['goals', 'risks'], arc: [2, 2.5], caption: '<b>Volta 3 · projeto.</b> Novos objetivos e nova análise de riscos, agora sobre a arquitetura e o projeto do software.' },
        { nodes: ['develop', 'planning'], arc: [2.5, 3], caption: '<b>Volta 3.</b> Projeto do produto, verificação e plano de integração e testes.' },
        { nodes: ['goals', 'risks', 'develop'], arc: [3, 3.5], caption: '<b>Volta 4.</b> Projeto detalhado, <b>código, testes e entrega</b>. O que diferencia o espiral é que o risco foi tratado <b>explicitamente em todas as voltas</b>.' },
      ],
      facts: [
        { label: WHEN, text: 'Projetos grandes, caros e com riscos técnicos altos.' },
        { label: STRENGTH, text: 'Risco tratado cedo e de forma explícita; une prototipação e cascata.' },
        { label: RISK, text: 'Exige especialistas em risco; complexo e caro para projetos pequenos.' },
      ],
    },
    {
      id: 'vmodel',
      name: 'Modelo V',
      summary: 'O lado esquerdo <b>desce</b> especificando; o lado direito <b>sobe</b> testando. Cada linha tracejada liga um artefato ao teste que o verifica.',
      width: 680,
      height: 360,
      nodes: [
        { id: 'user', label: 'Requisitos\ndo usuário', x: 70, y: 40, width: 114, color: 'var(--blue)' },
        { id: 'system', label: 'Requisitos\ndo sistema', x: 135, y: 110, width: 114, color: 'var(--teal)' },
        { id: 'architecture', label: 'Projeto de\narquitetura', x: 200, y: 180, width: 114, color: 'var(--green)' },
        { id: 'detail', label: 'Projeto\ndetalhado', x: 265, y: 250, width: 114, color: 'var(--purple)' },
        { id: 'code', label: 'Codificação', x: 340, y: 322, width: 124, color: 'var(--yellow)' },
        { id: 'unit', label: 'Teste de\nunidade', x: 415, y: 250, width: 114, color: 'var(--purple)' },
        { id: 'integration', label: 'Teste de\nintegração', x: 480, y: 180, width: 114, color: 'var(--green)' },
        { id: 'systemTest', label: 'Teste de\nsistema', x: 545, y: 110, width: 114, color: 'var(--teal)' },
        { id: 'acceptance', label: 'Teste de\naceitação', x: 610, y: 40, width: 114, color: 'var(--blue)' },
      ],
      edges: [
        { from: 'user', to: 'system' },
        { from: 'system', to: 'architecture' },
        { from: 'architecture', to: 'detail' },
        { from: 'detail', to: 'code' },
        { from: 'code', to: 'unit' },
        { from: 'unit', to: 'integration' },
        { from: 'integration', to: 'systemTest' },
        { from: 'systemTest', to: 'acceptance' },
        { from: 'detail', to: 'unit', dashed: true, kind: 'line' },
        { from: 'architecture', to: 'integration', dashed: true, kind: 'line' },
        { from: 'system', to: 'systemTest', dashed: true, kind: 'line' },
        { from: 'user', to: 'acceptance', dashed: true, kind: 'line' },
      ],
      steps: [
        { nodes: ['user'], caption: '<b>Requisitos do usuário.</b> O que o cliente precisa. O plano de <b>teste de aceitação</b> já nasce aqui.' },
        { nodes: ['system'], edges: [0], caption: '<b>Requisitos do sistema.</b> Especificação detalhada das funções e restrições; origem do plano de <b>teste de sistema</b>.' },
        { nodes: ['architecture'], edges: [1], caption: '<b>Projeto de arquitetura.</b> Módulos e interfaces; origem do plano de <b>teste de integração</b>.' },
        { nodes: ['detail'], edges: [2], caption: '<b>Projeto detalhado.</b> Lógica interna de cada módulo; origem dos <b>testes de unidade</b>.' },
        { nodes: ['code'], edges: [3], caption: '<b>Codificação.</b> O vértice do V: a partir daqui o processo sobe verificando.' },
        { nodes: ['unit', 'detail'], edges: [4, 8], caption: '<b>Teste de unidade</b> verifica cada módulo contra o <b>projeto detalhado</b>.' },
        { nodes: ['integration', 'architecture'], edges: [5, 9], caption: '<b>Teste de integração</b> verifica as interfaces entre módulos contra o <b>projeto de arquitetura</b>.' },
        { nodes: ['systemTest', 'system'], edges: [6, 10], caption: '<b>Teste de sistema</b> verifica o sistema completo contra os <b>requisitos do sistema</b>.' },
        { nodes: ['acceptance', 'user'], edges: [7, 11], caption: '<b>Teste de aceitação</b>: o cliente valida o sistema contra os <b>requisitos do usuário</b>.' },
      ],
      facts: [
        { label: WHEN, text: 'Sistemas em que a verificação é crítica e os requisitos são estáveis.' },
        { label: STRENGTH, text: 'Testes planejados desde o início, com rastreabilidade.' },
        { label: RISK, text: 'Herda a rigidez do cascata.' },
      ],
    },
    {
      id: 'rup',
      name: 'RUP',
      summary: 'Quatro <b>fases</b> (o tempo) atravessadas por <b>fluxos de trabalho</b> (as atividades). Cada fase tem uma ou mais iterações.',
      width: 640,
      height: 300,
      nodes: [
        { id: 'inception', label: 'Concepção', x: 90, y: 60, width: 130, height: 50, color: 'var(--blue)' },
        { id: 'elaboration', label: 'Elaboração', x: 243, y: 60, width: 130, height: 50, color: 'var(--green)' },
        { id: 'construction', label: 'Construção', x: 397, y: 60, width: 130, height: 50, color: 'var(--purple)' },
        { id: 'transition', label: 'Transição', x: 550, y: 60, width: 130, height: 50, color: 'var(--yellow)' },
        { id: 'flowInception', label: 'negócio e\nrequisitos', x: 90, y: 140, shape: 'label', color: 'var(--blue)' },
        { id: 'flowElaboration', label: 'análise, projeto\ne arquitetura', x: 243, y: 140, shape: 'label', color: 'var(--green)' },
        { id: 'flowConstruction', label: 'implementação\ne teste', x: 397, y: 140, shape: 'label', color: 'var(--purple)' },
        { id: 'flowTransition', label: 'implantação\ne treinamento', x: 550, y: 140, shape: 'label', color: 'var(--yellow)' },
        { id: 'support', label: 'Fluxos de apoio: gerência de configuração e mudanças · gerência de projeto · ambiente', x: 320, y: 235, width: 610, height: 42, color: 'var(--indigo)' },
      ],
      edges: [
        { from: 'inception', to: 'elaboration' },
        { from: 'elaboration', to: 'construction' },
        { from: 'construction', to: 'transition' },
      ],
      steps: [
        { nodes: ['inception', 'flowInception'], caption: '<b>Concepção.</b> Estabelece o <b>caso de negócio</b>: escopo, atores, principais casos de uso e viabilidade. Marco: <i>objetivos do ciclo de vida</i>.' },
        { nodes: ['elaboration', 'flowElaboration'], edges: [0], caption: '<b>Elaboração.</b> Entende o domínio, define a <b>arquitetura</b> e trata os <b>riscos</b> mais altos. Marco: <i>arquitetura do ciclo de vida</i>.' },
        { nodes: ['construction', 'flowConstruction'], edges: [1], caption: '<b>Construção.</b> Projeto, programação e teste em iterações, até o sistema funcionar. Marco: <i>capacidade operacional inicial</i>.' },
        { nodes: ['transition', 'flowTransition'], edges: [2], caption: '<b>Transição.</b> O sistema vai para o ambiente do usuário: implantação, treinamento e ajustes. Marco: <i>release do produto</i>.' },
        { nodes: ['support'], caption: '<b>Fluxos de apoio</b> acompanham todas as fases. E atenção: requisitos, projeto, código e teste acontecem em <b>todas</b> as fases, só muda a intensidade.' },
        { nodes: ['inception', 'transition'], caption: '<b>Novo ciclo.</b> Cada passagem pelas quatro fases gera uma <b>versão</b> do produto; as seguintes são ciclos de evolução.' },
      ],
      facts: [
        { label: WHEN, text: 'Projetos orientados a objetos, de médio e grande porte, com UML.' },
        { label: STRENGTH, text: 'Iterativo, dirigido por casos de uso e centrado na arquitetura.' },
        { label: RISK, text: 'Pesado para equipes pequenas se não for adaptado.' },
      ],
    },
  ],
};

export const chooseModelGame: ClassifierConfig = {
  id: 'choose',
  label: '⚖️ Qual modelo?',
  title: 'Qual modelo de processo você indicaria?',
  intro: 'Leia o cenário do projeto e escolha o modelo de ciclo de vida <b>mais adequado</b>.',
  categories: [
    { id: 'waterfall', label: 'Cascata', hint: 'requisitos estáveis', color: 'var(--blue)' },
    { id: 'prototyping', label: 'Prototipação', hint: 'requisitos vagos', color: 'var(--pink)' },
    { id: 'incremental', label: 'Incremental', hint: 'valor cedo, em partes', color: 'var(--green)' },
    { id: 'spiral', label: 'Espiral', hint: 'risco alto', color: 'var(--yellow)' },
  ],
  items: [
    { text: 'O cliente diz: "não sei descrever a tela, mas quando eu vir eu sei se é isso".', category: 'prototyping', explanation: 'Requisitos de interface incertos pedem um protótipo para que o cliente reaja a algo concreto.' },
    { text: 'Sistema de folha de pagamento com regras definidas em lei, que não mudam durante o projeto; o contrato exige um documento aprovado por fase.', category: 'waterfall', explanation: 'Requisitos estáveis e documentação por fase são o cenário clássico do cascata.' },
    { text: 'Projeto de grande porte para controle de satélite, com tecnologia inédita e alto custo de falha. A diretoria quer reavaliar a continuidade a cada etapa.', category: 'spiral', explanation: 'Alto risco técnico e decisão de continuar a cada ciclo: modelo espiral.' },
    { text: 'A loja precisa começar a vender on-line em dois meses; relatórios e programa de fidelidade podem vir depois.', category: 'incremental', explanation: 'Requisitos priorizáveis e necessidade de valor cedo: entrega incremental, começando pelo núcleo.' },
    { text: 'Os usuários nunca usaram um sistema parecido e discordam entre si sobre o que ele deve fazer.', category: 'prototyping', explanation: 'A prototipação ajuda a descobrir e negociar requisitos nebulosos.' },
    { text: 'Migração de um sistema existente para uma nova plataforma, mantendo exatamente as mesmas funções, já documentadas.', category: 'waterfall', explanation: 'Os requisitos já são conhecidos e não devem mudar.' },
    { text: 'O orçamento só será liberado em parcelas, e o cliente quer usar o que estiver pronto ao fim de cada parcela.', category: 'incremental', explanation: 'Cada parcela financia um incremento utilizável.' },
    { text: 'Ninguém sabe se o algoritmo de reconhecimento atingirá a precisão exigida; é preciso investigar alternativas antes de investir no restante.', category: 'spiral', explanation: 'O espiral trata o risco primeiro, com protótipos e análises, antes de comprometer mais recursos.' },
    { text: 'Sistema embarcado cujo hardware é fabricado em paralelo; as especificações de interface foram congeladas e assinadas pelas duas equipes.', category: 'waterfall', explanation: 'Especificação congelada e várias equipes coordenadas por documentos favorecem o cascata.' },
    { text: 'O produto tem um núcleo obrigatório e dezenas de funções opcionais; o cliente quer priorizá-las conforme for usando o sistema.', category: 'incremental', explanation: 'A experiência com os primeiros incrementos orienta a prioridade dos seguintes.' },
    { text: 'Projeto militar de longo prazo em que cada fase só é contratada após uma avaliação formal das alternativas e das ameaças ao cronograma e ao custo.', category: 'spiral', explanation: 'Avaliar alternativas e riscos a cada volta e decidir sobre a continuidade é a essência do espiral.' },
    { text: 'A equipe quer validar com os usuários, em uma semana, três alternativas de fluxo de navegação antes de especificar o sistema.', category: 'prototyping', explanation: 'Protótipos descartáveis servem exatamente para validar alternativas antes da especificação.' },
  ],
};
