import type { ClassifierConfig } from '../../components/ClassifierGame';
import type { DiagramConfig } from '../../components/DiagramPlayer';

export const requirementsLabTitle: string = 'Laboratório · Oficina de requisitos';

export const kindsGame: ClassifierConfig = {
  id: 'kinds',
  label: '🧮 RF × RNF',
  title: 'Funcional, não funcional ou de domínio?',
  intro: 'Pergunte-se: isto é <b>o que o sistema faz</b>, uma <b>restrição de qualidade</b> ou uma regra que vem do <b>domínio</b> da aplicação?',
  rounds: 12,
  categories: [
    { id: 'rf', label: 'Funcional', hint: 'o que o sistema faz', color: 'var(--blue)' },
    { id: 'rnf', label: 'Não funcional', hint: 'restrição ou qualidade', color: 'var(--green)' },
    { id: 'domain', label: 'De domínio', hint: 'regra da área de aplicação', color: 'var(--yellow)' },
  ],
  items: [
    { text: 'O aluno poderá consultar o histórico escolar e baixá-lo em PDF.', category: 'rf', explanation: 'É um serviço que o sistema oferece ao usuário.' },
    { text: 'A autenticação no portal não deve levar mais de 1 segundo com 5.000 usuários simultâneos.', category: 'rnf', explanation: 'Desempenho: restrição de qualidade sobre um serviço.' },
    { text: 'O professor poderá lançar notas e frequências parciais por turma.', category: 'rf', explanation: 'Função disponível a um usuário.' },
    { text: 'O sistema deve manter cópias de segurança criptografadas a cada 12 horas.', category: 'rnf', explanation: 'Confiabilidade e segurança do sistema como um todo.' },
    { text: 'A aprovação exige média final igual ou superior a 6,0 e frequência mínima de 75%, conforme o regulamento da universidade.', category: 'domain', explanation: 'A regra vem do domínio acadêmico (regulamento), não da preferência de um usuário.' },
    { text: 'O sistema deve emitir um boleto para cada mensalidade em aberto.', category: 'rf', explanation: 'Serviço oferecido pelo sistema.' },
    { text: 'A interface deve funcionar nas duas versões mais recentes dos navegadores Chrome, Firefox e Edge.', category: 'rnf', explanation: 'Portabilidade: restrição de produto.' },
    { text: 'O cálculo de juros de mora deve seguir a fórmula definida pelo Banco Central para o setor.', category: 'domain', explanation: 'Norma do domínio financeiro imposta ao sistema.' },
    { text: 'O sistema deve enviar um e-mail de confirmação quando a matrícula for efetivada.', category: 'rf', explanation: 'Reação do sistema a um evento: comportamento funcional.' },
    { text: 'O sistema deve ficar disponível 99,5% do tempo em dias letivos.', category: 'rnf', explanation: 'Disponibilidade é atributo de confiabilidade.' },
    { text: 'Um novo atendente deve conseguir registrar um empréstimo após 30 minutos de treinamento.', category: 'rnf', explanation: 'Usabilidade expressa de forma mensurável.' },
    { text: 'O bibliotecário poderá registrar a devolução de um exemplar e o sistema calculará a multa por atraso.', category: 'rf', explanation: 'Dois serviços do sistema: registrar devolução e calcular multa.' },
    { text: 'Por norma da aviação civil, a distância de frenagem deve considerar a inclinação da pista e as condições do tempo.', category: 'domain', explanation: 'Conhecimento especializado do domínio que o sistema precisa respeitar.' },
    { text: 'O sistema deve ser entregue em três etapas, a primeira em até 90 dias.', category: 'rnf', explanation: 'Requisito de entrega: RNF organizacional.' },
    { text: 'O gerente poderá gerar o relatório mensal de vendas por região.', category: 'rf', explanation: 'Funcionalidade de emissão de relatório.' },
    { text: 'As senhas devem ser armazenadas com um algoritmo de hash resistente a ataques de força bruta.', category: 'rnf', explanation: 'Segurança: restrição sobre como o sistema opera.' },
  ],
};

export const nfrGame: ClassifierConfig = {
  id: 'nfr',
  label: '🛡️ Tipos de RNF',
  title: 'De produto, organizacional ou externo?',
  intro: 'Todos os cards são requisitos <b>não funcionais</b>. Descubra de onde cada um vem, segundo Sommerville.',
  categories: [
    { id: 'product', label: 'De produto', hint: 'comportamento do software', color: 'var(--blue)' },
    { id: 'organizational', label: 'Organizacional', hint: 'políticas e padrões', color: 'var(--purple)' },
    { id: 'external', label: 'Externo', hint: 'leis, ética, outros sistemas', color: 'var(--yellow)' },
  ],
  items: [
    { text: 'O tempo de resposta da busca não pode passar de 1,5 segundo.', category: 'product', explanation: 'Eficiência (desempenho) é requisito de produto.' },
    { text: 'O sistema deve ser implementado em Java.', category: 'organizational', explanation: 'Requisito de implementação, imposto pela organização.' },
    { text: 'O sistema deve atender à lei de proteção de dados pessoais.', category: 'external', explanation: 'Requisito legal: externo.' },
    { text: 'A documentação deve seguir o padrão de processo adotado pela empresa.', category: 'organizational', explanation: 'Requisito de padrões.' },
    { text: 'O aplicativo deve rodar em Android e iOS.', category: 'product', explanation: 'Portabilidade é requisito de produto.' },
    { text: 'O sistema deve trocar dados com o sistema da Receita Federal no formato exigido por ela.', category: 'external', explanation: 'Interoperabilidade com sistemas de outras organizações: externo.' },
    { text: 'A primeira versão deve ser entregue até o início do próximo semestre.', category: 'organizational', explanation: 'Requisito de entrega.' },
    { text: 'O sistema não deve ficar indisponível por mais de 5 minutos por mês.', category: 'product', explanation: 'Confiabilidade é requisito de produto.' },
    { text: 'O sistema não pode exibir conteúdo ofensivo aos usuários.', category: 'external', explanation: 'Requisito ético: externo.' },
    { text: 'O sistema deve ocupar no máximo 200 MB no dispositivo.', category: 'product', explanation: 'Eficiência (espaço) é requisito de produto.' },
    { text: 'Todo o código deve passar por revisão antes de ser integrado, conforme a política da fábrica de software.', category: 'organizational', explanation: 'Política interna de desenvolvimento.' },
    { text: 'O sistema médico deve ser certificado pelo órgão regulador de saúde antes de entrar em uso.', category: 'external', explanation: 'Exigência regulatória: externa.' },
  ],
};

export const techniquesGame: ClassifierConfig = {
  id: 'techniques',
  label: '🎤 Técnicas',
  title: 'Qual técnica de levantamento usar?',
  intro: 'Cada situação pede uma técnica. Escolha a <b>mais adequada</b>.',
  categories: [
    { id: 'interview', label: 'Entrevista', hint: 'poucas pessoas, em profundidade', color: 'var(--blue)' },
    { id: 'survey', label: 'Questionário', hint: 'muita gente, dados padronizados', color: 'var(--green)' },
    { id: 'observation', label: 'Etnografia', hint: 'observar o trabalho real', color: 'var(--yellow)' },
    { id: 'workshop', label: 'Workshop / JAD', hint: 'consenso em grupo', color: 'var(--purple)' },
    { id: 'prototype', label: 'Prototipação', hint: 'mostrar para descobrir', color: 'var(--pink)' },
  ],
  items: [
    { text: 'A empresa tem 1.200 vendedores em 40 cidades e você precisa saber quais relatórios eles mais usam.', category: 'survey', explanation: 'Muitos usuários dispersos e pergunta objetiva: questionário.' },
    { text: 'O diretor financeiro é a única pessoa que conhece as regras de fechamento contábil.', category: 'interview', explanation: 'Um especialista-chave: entrevista em profundidade.' },
    { text: 'Os operadores do centro de controle dizem que "fazem tudo no automático" e não conseguem explicar os passos.', category: 'observation', explanation: 'Conhecimento tácito só aparece observando o trabalho real.' },
    { text: 'Vendas, estoque e financeiro discordam sobre como deve funcionar a aprovação de pedidos.', category: 'workshop', explanation: 'Reunir as partes com um facilitador para negociar e obter consenso.' },
    { text: 'O cliente não consegue imaginar como deveria ser a tela de agendamento.', category: 'prototype', explanation: 'Um protótipo de interface dá algo concreto para o cliente reagir.' },
    { text: 'Você quer medir a satisfação de todos os alunos com o portal atual, em uma escala de 1 a 5.', category: 'survey', explanation: 'Dados quantificáveis de uma população grande.' },
    { text: 'É preciso entender como os enfermeiros realmente registram a medicação durante o plantão, incluindo os "jeitinhos".', category: 'observation', explanation: 'A etnografia revela o processo real, diferente do processo formal.' },
    { text: 'Em três dias, usuários-chave e desenvolvedores precisam fechar juntos o escopo do sistema.', category: 'workshop', explanation: 'Sessões intensivas e estruturadas são a proposta do JAD.' },
    { text: 'Há duas ideias de fluxo de navegação e ninguém sabe qual os usuários vão preferir.', category: 'prototype', explanation: 'Construir e testar as alternativas com usuários.' },
    { text: 'Você precisa explorar, sem roteiro fixo, as expectativas da gerente que encomendou o sistema.', category: 'interview', explanation: 'Entrevista aberta: exploratória, sem agenda predefinida.' },
  ],
};

export const requirementsDiagram: DiagramConfig = {
  id: 'process',
  label: '🔁 Processo e casos de uso',
  title: 'Do problema ao documento de requisitos',
  models: [
    {
      id: 'sommerville',
      name: 'Processo de requisitos',
      summary: 'Quatro atividades, cada uma com o seu produto. No fim, tudo converge para o <b>documento de requisitos</b>.',
      width: 640,
      height: 300,
      nodes: [
        { id: 'feasibility', label: 'Estudo de\nviabilidade', x: 82, y: 60, width: 126, color: 'var(--yellow)' },
        { id: 'elicitation', label: 'Elicitação\ne análise', x: 240, y: 60, width: 126, color: 'var(--blue)' },
        { id: 'specification', label: 'Especificação', x: 400, y: 60, width: 126, color: 'var(--green)' },
        { id: 'validation', label: 'Validação', x: 558, y: 60, width: 126, color: 'var(--purple)' },
        { id: 'report', label: 'Relatório de\nviabilidade', x: 82, y: 175, width: 140, height: 52, shape: 'ellipse', color: 'var(--yellow)' },
        { id: 'models', label: 'Modelos\ndo sistema', x: 240, y: 175, width: 140, height: 52, shape: 'ellipse', color: 'var(--blue)' },
        { id: 'requirements', label: 'Requisitos de\nusuário e de sistema', x: 400, y: 175, width: 150, height: 52, shape: 'ellipse', color: 'var(--green)' },
        { id: 'document', label: 'Documento\nde requisitos', x: 558, y: 175, width: 140, height: 52, shape: 'ellipse', color: 'var(--purple)' },
        { id: 'management', label: 'Gerenciamento de requisitos: controle de mudanças e rastreabilidade', x: 320, y: 262, width: 600, height: 40, color: 'var(--indigo)' },
      ],
      edges: [
        { from: 'feasibility', to: 'elicitation' },
        { from: 'elicitation', to: 'specification' },
        { from: 'specification', to: 'validation' },
        { from: 'feasibility', to: 'report', dashed: true },
        { from: 'elicitation', to: 'models', dashed: true },
        { from: 'specification', to: 'requirements', dashed: true },
        { from: 'validation', to: 'document', dashed: true },
      ],
      steps: [
        { nodes: ['feasibility', 'report'], edges: [3], caption: '<b>Estudo de viabilidade.</b> Rápido e barato: o sistema contribui para os objetivos da organização? Pode ser feito com a tecnologia e o orçamento atuais? Integra-se aos outros sistemas? Resultado: um <b>relatório</b> que recomenda seguir ou não.' },
        { nodes: ['elicitation', 'models'], edges: [0, 4], caption: '<b>Elicitação e análise.</b> Descobrir os requisitos com os stakeholders por meio de entrevistas, observação, cenários e protótipos. É a etapa mais difícil: as pessoas nem sempre sabem o que querem.' },
        { nodes: ['specification', 'requirements'], edges: [1, 5], caption: '<b>Especificação.</b> Traduzir o que foi levantado em requisitos de <b>usuário</b> (alto nível) e de <b>sistema</b> (detalhados).' },
        { nodes: ['validation', 'document'], edges: [2, 6], caption: '<b>Validação.</b> Conferir validade, consistência, completeza, realismo e verificabilidade. O que passa vira o <b>documento de requisitos</b>.' },
        { nodes: ['management'], caption: '<b>Gerenciamento de requisitos.</b> Requisitos mudam. Esta atividade acompanha todo o processo, analisando o impacto de cada mudança com ajuda da <b>rastreabilidade</b>.' },
      ],
    },
    {
      id: 'elicitation',
      name: 'Espiral da elicitação',
      summary: 'Dentro da elicitação e análise, quatro passos se repetem até os requisitos estabilizarem.',
      width: 640,
      height: 300,
      nodes: [
        { id: 'discovery', label: 'Descoberta\nde requisitos', x: 320, y: 45, width: 150, color: 'var(--blue)' },
        { id: 'classification', label: 'Classificação\ne organização', x: 520, y: 150, width: 150, color: 'var(--green)' },
        { id: 'negotiation', label: 'Priorização\ne negociação', x: 320, y: 255, width: 150, color: 'var(--yellow)' },
        { id: 'documentation', label: 'Documentação', x: 120, y: 150, width: 150, color: 'var(--purple)' },
      ],
      edges: [
        { from: 'discovery', to: 'classification', bend: -24 },
        { from: 'classification', to: 'negotiation', bend: -24 },
        { from: 'negotiation', to: 'documentation', bend: -24 },
        { from: 'documentation', to: 'discovery', bend: -24 },
      ],
      steps: [
        { nodes: ['discovery'], caption: '<b>Descoberta.</b> Interagir com os stakeholders para coletar os requisitos e os requisitos de domínio.' },
        { nodes: ['classification'], edges: [0], caption: '<b>Classificação e organização.</b> Agrupar requisitos relacionados em conjuntos coerentes.' },
        { nodes: ['negotiation'], edges: [1], caption: '<b>Priorização e negociação.</b> Com vários stakeholders, os requisitos <b>conflitam</b>. Aqui se decide o que é mais importante e se resolvem os conflitos.' },
        { nodes: ['documentation'], edges: [2], caption: '<b>Documentação.</b> Os requisitos são registrados e servem de entrada para a próxima volta.' },
        { nodes: ['discovery'], edges: [3], caption: 'O ciclo se <b>repete</b>: a cada volta o entendimento melhora, até o documento de requisitos ficar completo.' },
      ],
    },
    {
      id: 'usecase',
      name: 'Diagrama de casos de uso',
      summary: 'Uma loja virtual. Avance os passos e repare na <b>direção de cada seta</b>.',
      width: 640,
      height: 340,
      noToken: true,
      nodes: [
        { id: 'customer', label: 'Cliente', x: 70, y: 105, shape: 'actor', color: 'var(--blue)' },
        { id: 'vip', label: 'Cliente VIP', x: 70, y: 265, shape: 'actor', color: 'var(--purple)' },
        { id: 'order', label: 'Realizar pedido', x: 290, y: 150, width: 170, height: 60, shape: 'ellipse', color: 'var(--green)' },
        { id: 'login', label: 'Autenticar usuário', x: 530, y: 70, width: 180, height: 56, shape: 'ellipse', color: 'var(--yellow)' },
        { id: 'coupon', label: 'Aplicar cupom\nde desconto', x: 530, y: 260, width: 180, height: 60, shape: 'ellipse', color: 'var(--pink)' },
      ],
      edges: [
        { from: 'customer', to: 'order', kind: 'line' },
        { from: 'order', to: 'login', dashed: true, label: '«include»' },
        { from: 'coupon', to: 'order', dashed: true, label: '«extend»' },
        { from: 'vip', to: 'customer', kind: 'generalization' },
      ],
      steps: [
        { nodes: ['customer'], caption: '<b>Ator.</b> "Cliente" é um <b>papel</b> externo ao sistema. Poderia ser também outro sistema ou um dispositivo.' },
        { nodes: ['customer', 'order'], edges: [0], caption: '<b>Associação.</b> A linha (sem seta obrigatória) indica que o ator participa do caso de uso "Realizar pedido", que entrega um resultado de valor.' },
        { nodes: ['order', 'login'], edges: [1], caption: '<b>«include».</b> "Realizar pedido" <b>sempre</b> executa "Autenticar usuário". A seta <b>sai do caso base</b> e aponta para o incluído. Serve para reutilizar um comportamento comum a vários casos.' },
        { nodes: ['coupon', 'order'], edges: [2], caption: '<b>«extend».</b> "Aplicar cupom" só acontece <b>se</b> o cliente tiver um cupom. A seta sai do caso que <b>estende</b> e aponta para o <b>caso base</b>, o contrário do include.' },
        { nodes: ['vip', 'customer'], edges: [3], caption: '<b>Generalização.</b> "Cliente VIP" é um tipo de "Cliente" e herda as suas associações. O triângulo vazado aponta para o elemento <b>mais geral</b>.' },
        { nodes: ['order', 'login', 'coupon'], edges: [1, 2], caption: '<b>Resumo para a prova:</b> include = obrigatório, base → incluído. Extend = opcional, extensão → base. O diagrama <b>não</b> mostra ordem nem fluxo: isso fica na descrição textual do caso de uso.' },
      ],
    },
  ],
};
