import type { ClassifierConfig } from '../../components/ClassifierGame';
import type { BoundaryConfig } from '../../labs/testing/BoundaryPanel';
import type { CyclomaticConfig } from '../../labs/testing/CyclomaticPanel';

export const testingLabTitle: string = 'Laboratório · Bancada de testes';

export const boundaryWorkbench: BoundaryConfig = {
  id: 'boundary',
  label: '⬛ Valor limite',
  title: 'Classes de equivalência e valores limite',
  intro: 'Técnica <b>caixa-preta</b>. Adicione valores de teste até cobrir <b>todas as classes</b> (uma amostra de cada) e <b>todos os limites</b> (as bolinhas na base).',
  inputLabel: 'Valor de entrada:',
  add: 'Adicionar caso de teste',
  suggest: 'Mostrar o conjunto mínimo',
  clear: 'Limpar',
  classesLabel: (hit: number, total: number): string => 'Classes de equivalência cobertas: ' + hit + ' de ' + total,
  boundariesLabel: (hit: number, total: number): string => 'Valores limite exercitados: ' + hit + ' de ' + total,
  validLabel: 'classe válida',
  invalidLabel: 'classe inválida',
  outsideLabel: 'fora da faixa desenhada',
  boundaryBadge: 'limite',
  headers: { value: 'Entrada', partition: 'Classe', outcome: 'Resultado esperado' },
  emptyTests: 'Nenhum caso de teste ainda. Comece pelos valores que ficam exatamente na fronteira.',
  done: (tests: number): string =>
    '🎯 <b>Cobertura completa com ' + tests + ' casos de teste.</b> Repare que os valores limite já garantem uma amostra de cada classe: é por isso que as duas técnicas andam juntas.',
  hint: 'Todo caso de teste precisa de <b>resultado esperado</b>. Sem ele, não há como dizer se o teste passou.',
  scenarios: [
    {
      id: 'age',
      name: 'Idade para cadastro',
      rule: 'Regra: o cadastro aceita pessoas com idade <b>de 18 a 65 anos</b> (valor inteiro). Fora disso, o sistema deve recusar.',
      step: 1,
      partitions: [
        { label: 'menor que 18', from: 10, to: 17, valid: false, outcome: 'recusa: idade abaixo do mínimo' },
        { label: 'de 18 a 65', from: 18, to: 65, valid: true, outcome: 'cadastro aceito' },
        { label: 'maior que 65', from: 66, to: 73, valid: false, outcome: 'recusa: idade acima do máximo' },
      ],
    },
    {
      id: 'grade',
      name: 'Nota final',
      rule: 'Regra: a nota vai de <b>0,0 a 10,0</b>, com uma casa decimal. Nota <b>maior ou igual a 6,0</b> aprova; abaixo disso, reprova. Valores fora da escala são inválidos.',
      step: 0.1,
      partitions: [
        { label: 'abaixo de 0', from: -1, to: -0.1, valid: false, outcome: 'erro: nota inválida' },
        { label: 'de 0,0 a 5,9', from: 0, to: 5.9, valid: true, outcome: 'reprovado' },
        { label: 'de 6,0 a 10,0', from: 6, to: 10, valid: true, outcome: 'aprovado' },
        { label: 'acima de 10', from: 10.1, to: 11, valid: false, outcome: 'erro: nota inválida' },
      ],
    },
    {
      id: 'order',
      name: 'Itens do pedido',
      rule: 'Regra: um pedido tem <b>de 1 a 10 itens</b>. A partir de <b>6 itens</b>, o frete é grátis.',
      step: 1,
      partitions: [
        { label: '0 ou menos', from: -2, to: 0, valid: false, outcome: 'recusa: pedido vazio' },
        { label: 'de 1 a 5', from: 1, to: 5, valid: true, outcome: 'pedido aceito, frete cobrado' },
        { label: 'de 6 a 10', from: 6, to: 10, valid: true, outcome: 'pedido aceito, frete grátis' },
        { label: '11 ou mais', from: 11, to: 13, valid: false, outcome: 'recusa: acima do máximo' },
      ],
    },
  ],
};

export const cyclomaticWorkbench: CyclomaticConfig = {
  id: 'cyclomatic',
  label: '⬜ Caminho básico',
  title: 'Grafo de fluxo e complexidade ciclomática',
  intro: 'Técnica <b>caixa-branca</b>. Cada nó do grafo é um trecho do código; cada decisão abre dois caminhos. Clique em um caminho para vê-lo percorrendo o código.',
  nodesLabel: 'Nós (N)',
  edgesLabel: 'Arestas (E)',
  predicatesLabel: 'Predicados (P)',
  regionsLabel: 'Regiões',
  formulaTitles: { edges: 'Por arestas e nós', predicates: 'Por predicados', regions: 'Por regiões (com a externa)' },
  pathsTitle: (count: number): string => 'Conjunto básico: ' + count + ' caminhos independentes = ' + count + ' casos de teste',
  pathLabel: (index: number): string => 'Caminho ' + index,
  pathHint: 'Um caminho é <b>independente</b> quando percorre pelo menos uma aresta que os anteriores não percorreram.',
  programs: [
    {
      id: 'status',
      name: 'Duas decisões',
      code: [
        'function status(grade, attendance) {',
        '  if (attendance < 75) {',
        "    return 'FAILED: ATTENDANCE';",
        '  }',
        '  if (grade >= 6) {',
        "    return 'APPROVED';",
        '  }',
        "  return 'FAILED: GRADE';",
        '}',
      ],
      width: 280,
      height: 300,
      nodes: [
        { id: '1', x: 140, y: 30, lines: [2] },
        { id: '2', x: 60, y: 110, lines: [3] },
        { id: '3', x: 200, y: 110, lines: [5] },
        { id: '4', x: 140, y: 190, lines: [6] },
        { id: '5', x: 245, y: 190, lines: [8] },
        { id: '6', x: 140, y: 270, lines: [9] },
      ],
      edges: [
        { from: '1', to: '2' }, { from: '1', to: '3' }, { from: '2', to: '6' }, { from: '3', to: '4' },
        { from: '3', to: '5' }, { from: '4', to: '6' }, { from: '5', to: '6' },
      ],
      regions: 3,
      paths: [
        { nodes: ['1', '2', '6'], description: '<b>Caminho 1 (1-2-6).</b> Caso de teste: frequência 60, nota 8. Esperado: reprovado por frequência.' },
        { nodes: ['1', '3', '4', '6'], description: '<b>Caminho 2 (1-3-4-6).</b> Caso de teste: frequência 90, nota 7. Esperado: aprovado.' },
        { nodes: ['1', '3', '5', '6'], description: '<b>Caminho 3 (1-3-5-6).</b> Caso de teste: frequência 90, nota 4. Esperado: reprovado por nota.' },
      ],
    },
    {
      id: 'loop',
      name: 'Laço com decisão',
      code: [
        'function countApproved(grades) {',
        '  let approved = 0;',
        '  let i = 0;',
        '  while (i < grades.length) {',
        '    if (grades[i] >= 6) {',
        '      approved++;',
        '    }',
        '    i++;',
        '  }',
        '  return approved;',
        '}',
      ],
      width: 280,
      height: 300,
      nodes: [
        { id: '1', x: 120, y: 28, lines: [2, 3] },
        { id: '2', x: 120, y: 90, lines: [4] },
        { id: '3', x: 120, y: 152, lines: [5] },
        { id: '4', x: 195, y: 208, lines: [6] },
        { id: '5', x: 120, y: 264, lines: [8] },
        { id: '6', x: 225, y: 120, lines: [10] },
      ],
      edges: [
        { from: '1', to: '2' }, { from: '2', to: '3' }, { from: '2', to: '6' }, { from: '3', to: '4' },
        { from: '3', to: '5' }, { from: '4', to: '5' }, { from: '5', to: '2', bend: 85 },
      ],
      regions: 3,
      paths: [
        { nodes: ['1', '2', '6'], description: '<b>Caminho 1 (1-2-6).</b> Caso de teste: lista vazia. O laço não executa nenhuma vez. Esperado: 0.' },
        { nodes: ['1', '2', '3', '5', '2', '6'], description: '<b>Caminho 2 (1-2-3-5-2-6).</b> Caso de teste: [4]. Uma iteração, com a decisão falsa. Esperado: 0.' },
        { nodes: ['1', '2', '3', '4', '5', '2', '6'], description: '<b>Caminho 3 (1-2-3-4-5-2-6).</b> Caso de teste: [8]. Uma iteração, com a decisão verdadeira. Esperado: 1.' },
      ],
    },
    {
      id: 'shipping',
      name: 'Três decisões',
      code: [
        'function shipping(total, isMember, isRemote) {',
        '  let fee = 20;',
        '  if (total > 200) {',
        '    fee = 0;',
        '  } else if (isMember) {',
        '    fee = 10;',
        '  }',
        '  if (isRemote) {',
        '    fee += 15;',
        '  }',
        '  return fee;',
        '}',
      ],
      width: 280,
      height: 330,
      nodes: [
        { id: '1', x: 130, y: 26, lines: [2, 3] },
        { id: '2', x: 55, y: 105, lines: [4] },
        { id: '3', x: 195, y: 88, lines: [5] },
        { id: '4', x: 245, y: 150, lines: [6] },
        { id: '5', x: 130, y: 200, lines: [8] },
        { id: '6', x: 60, y: 256, lines: [9] },
        { id: '7', x: 130, y: 304, lines: [11] },
      ],
      edges: [
        { from: '1', to: '2' }, { from: '1', to: '3' }, { from: '2', to: '5' }, { from: '3', to: '4' }, { from: '3', to: '5' },
        { from: '4', to: '5' }, { from: '5', to: '6' }, { from: '5', to: '7' }, { from: '6', to: '7' },
      ],
      regions: 4,
      paths: [
        { nodes: ['1', '2', '5', '7'], description: '<b>Caminho 1 (1-2-5-7).</b> Caso de teste: total 300, não é sócio, entrega local. Esperado: frete 0.' },
        { nodes: ['1', '3', '5', '7'], description: '<b>Caminho 2 (1-3-5-7).</b> Caso de teste: total 100, não é sócio, entrega local. Esperado: frete 20.' },
        { nodes: ['1', '3', '4', '5', '7'], description: '<b>Caminho 3 (1-3-4-5-7).</b> Caso de teste: total 100, sócio, entrega local. Esperado: frete 10.' },
        { nodes: ['1', '2', '5', '6', '7'], description: '<b>Caminho 4 (1-2-5-6-7).</b> Caso de teste: total 300, não é sócio, entrega remota. Esperado: frete 15.' },
      ],
    },
  ],
};

export const levelsGame: ClassifierConfig = {
  id: 'levels',
  label: '🪜 Níveis',
  title: 'Em que nível de teste isso acontece?',
  intro: 'Do menor para o maior escopo: <b>unidade, integração, sistema, aceitação</b>.',
  categories: [
    { id: 'unit', label: 'Unidade', hint: 'um módulo isolado', color: 'var(--purple)' },
    { id: 'integration', label: 'Integração', hint: 'interfaces entre módulos', color: 'var(--green)' },
    { id: 'system', label: 'Sistema', hint: 'o sistema completo', color: 'var(--teal)' },
    { id: 'acceptance', label: 'Aceitação', hint: 'o cliente valida', color: 'var(--blue)' },
  ],
  items: [
    { text: 'O programador testa a função que calcula o dígito verificador do CPF, isolada do resto.', category: 'unit', explanation: 'Um único componente, testado isoladamente.' },
    { text: 'A equipe verifica se o módulo de pedidos passa corretamente os dados ao módulo de pagamento.', category: 'integration', explanation: 'O foco é a interface entre dois módulos.' },
    { text: 'Com o sistema inteiro montado no ambiente de homologação, testa-se o tempo de resposta com 1.000 usuários.', category: 'system', explanation: 'Sistema completo, incluindo requisitos não funcionais.' },
    { text: 'O cliente executa os seus cenários de negócio com dados reais para decidir se assina o recebimento.', category: 'acceptance', explanation: 'Validação pelo cliente contra os requisitos do usuário.' },
    { text: 'Um stub substitui o serviço de frete enquanto o módulo de carrinho é combinado com o de catálogo.', category: 'integration', explanation: 'Stubs e drivers são instrumentos da integração incremental.' },
    { text: 'Um grupo de usuários selecionados usa a versão beta no próprio local de trabalho.', category: 'acceptance', explanation: 'Teste beta é um teste de aceitação.' },
    { text: 'Um teste automatizado chama um método de uma classe com um valor limite e confere o retorno.', category: 'unit', explanation: 'Teste de unidade típico, como os feitos com JUnit.' },
    { text: 'A equipe independente derruba o banco de dados de propósito para ver se o sistema se recupera.', category: 'system', explanation: 'Teste de recuperação é um teste de sistema.' },
    { text: 'Depois de juntar os módulos de baixo nível, usa-se um driver para chamá-los e verificar a comunicação.', category: 'integration', explanation: 'Integração ascendente, com drivers.' },
    { text: 'Tenta-se burlar a autenticação da aplicação completa, já instalada no servidor.', category: 'system', explanation: 'Teste de segurança é um teste de sistema.' },
  ],
};

export const kindsGame: ClassifierConfig = {
  id: 'kinds',
  label: '🧰 Tipos',
  title: 'Que teste é esse?',
  intro: 'Identifique o tipo de teste pelo <b>objetivo</b> descrito.',
  categories: [
    { id: 'regression', label: 'Regressão', hint: 'nada quebrou com a mudança?', color: 'var(--blue)' },
    { id: 'smoke', label: 'Fumaça', hint: 'o básico funciona?', color: 'var(--teal)' },
    { id: 'performance', label: 'Desempenho', hint: 'carga esperada', color: 'var(--green)' },
    { id: 'stress', label: 'Estresse', hint: 'além do limite', color: 'var(--red)' },
    { id: 'security', label: 'Segurança', hint: 'resiste a ataques?', color: 'var(--purple)' },
    { id: 'recovery', label: 'Recuperação', hint: 'volta depois de falhar?', color: 'var(--yellow)' },
  ],
  items: [
    { text: 'Após alterar o cálculo de impostos, toda a suíte de testes antiga é executada de novo.', category: 'regression', explanation: 'Reteste para detectar efeitos colaterais da mudança.' },
    { text: 'A cada nova construção diária, roda-se uma bateria rápida para ver se o sistema ao menos inicia e faz login.', category: 'smoke', explanation: 'Teste de fumaça: verificação rápida antes dos testes aprofundados.' },
    { text: 'Mede-se o tempo de resposta do sistema com os 300 usuários simultâneos previstos no requisito.', category: 'performance', explanation: 'Carga dentro do previsto: desempenho.' },
    { text: 'Dispara-se dez vezes o volume máximo de requisições para descobrir em que ponto o sistema cai.', category: 'stress', explanation: 'Condições anormais, além do limite: estresse.' },
    { text: 'Especialistas tentam obter acesso a dados sem autorização, usando injeção de comandos.', category: 'security', explanation: 'Verifica os mecanismos de proteção.' },
    { text: 'O servidor é desligado durante uma transação para verificar se os dados voltam íntegros na retomada.', category: 'recovery', explanation: 'Força a falha e verifica a recuperação.' },
    { text: 'Corrigido o defeito 142, a equipe confirma que os relatórios que já funcionavam continuam corretos.', category: 'regression', explanation: 'Mudança no código pede regressão.' },
    { text: 'Reduz-se a memória disponível a um décimo do recomendado para observar o comportamento.', category: 'stress', explanation: 'Recursos anormalmente escassos: estresse.' },
    { text: 'Verifica-se se o sistema bloqueia a conta depois de várias tentativas de senha errada.', category: 'security', explanation: 'Mecanismo de proteção contra acesso indevido.' },
    { text: 'Confere-se se a consulta de saldo responde em menos de 2 segundos em condições normais de uso.', category: 'performance', explanation: 'Requisito de tempo sob carga normal.' },
    { text: 'Depois de uma queda de rede simulada, verifica-se se o sistema reinicia sozinho dentro do tempo especificado.', category: 'recovery', explanation: 'Tempo e correção da retomada.' },
    { text: 'Antes de liberar a versão para a equipe de testes, executa-se um roteiro mínimo das funções críticas.', category: 'smoke', explanation: 'Se a fumaça falha, nem vale a pena testar o resto.' },
  ],
};

export const boxGame: ClassifierConfig = {
  id: 'box',
  label: '🎁 Preta ou branca?',
  title: 'Caixa-preta ou caixa-branca?',
  intro: 'A pergunta é sempre: o caso de teste nasce da <b>especificação</b> ou da <b>estrutura do código</b>?',
  categories: [
    { id: 'black', label: 'Caixa-preta', hint: 'pela especificação', color: 'var(--indigo)' },
    { id: 'white', label: 'Caixa-branca', hint: 'pela estrutura do código', color: 'var(--yellow)' },
  ],
  items: [
    { text: 'Particionamento em classes de equivalência', category: 'black', explanation: 'As classes vêm do domínio de entrada descrito na especificação.' },
    { text: 'Teste de caminho básico', category: 'white', explanation: 'Deriva os casos do grafo de fluxo do código.' },
    { text: 'Análise de valor limite', category: 'black', explanation: 'Testa as fronteiras das classes de equivalência.' },
    { text: 'Cobertura de decisões (cada desvio verdadeiro e falso)', category: 'white', explanation: 'Critério de cobertura estrutural.' },
    { text: 'Teste de laços: zero, uma e várias iterações', category: 'white', explanation: 'Olha a estrutura de repetição do código.' },
    { text: 'Tabela de decisão construída a partir das regras de negócio', category: 'black', explanation: 'Combina condições e ações da especificação.' },
    { text: 'Teste baseado nos fluxos de um caso de uso', category: 'black', explanation: 'Parte dos requisitos, não do código.' },
    { text: 'Cálculo da complexidade ciclomática para definir quantos testes fazer', category: 'white', explanation: 'A métrica é obtida da lógica interna do programa.' },
    { text: 'Teste de fluxo de dados: onde cada variável é definida e usada', category: 'white', explanation: 'Exige conhecer o código.' },
    { text: 'Teste de aceitação conduzido pelo cliente', category: 'black', explanation: 'O cliente não conhece o código: observa o comportamento.' },
  ],
};

export const verificationGame: ClassifierConfig = {
  id: 'vv',
  label: '⚖️ V ou V?',
  title: 'Verificação ou validação?',
  intro: '<b>Verificação:</b> construímos corretamente (conforme a especificação)? <b>Validação:</b> construímos a coisa certa (o que o cliente precisa)?',
  categories: [
    { id: 'verification', label: 'Verificação', hint: 'conforme a especificação', color: 'var(--blue)' },
    { id: 'validation', label: 'Validação', hint: 'o que o cliente precisa', color: 'var(--green)' },
  ],
  items: [
    { text: 'Inspeção do código para conferir se ele segue o projeto detalhado.', category: 'verification', explanation: 'Compara um artefato com a sua especificação.' },
    { text: 'O cliente usa o sistema com dados reais e diz se ele resolve o problema do negócio.', category: 'validation', explanation: 'Confronta o produto com a necessidade real.' },
    { text: 'Teste de unidade que confere se a função devolve o que o documento de projeto define.', category: 'verification', explanation: 'Conformidade à especificação do módulo.' },
    { text: 'Demonstração de um protótipo para confirmar que as telas atendem ao que os usuários esperam.', category: 'validation', explanation: 'Verifica se estamos construindo a coisa certa.' },
    { text: 'Revisão do modelo de dados contra o documento de requisitos.', category: 'verification', explanation: 'Um artefato comparado ao anterior.' },
    { text: 'Teste beta com usuários no ambiente deles.', category: 'validation', explanation: 'Teste de aceitação é validação.' },
    { text: 'Análise estática automática para detectar violações do padrão de codificação.', category: 'verification', explanation: 'Técnica estática de verificação.' },
    { text: 'Reunião em que os stakeholders confirmam que os requisitos descrevem o sistema de que precisam.', category: 'validation', explanation: 'Validação de requisitos.' },
  ],
};
